public enum EGameMode {
  IDLE,
  MENU__STAFF,
  MENU__BUILDING,
  MENU__FURNITURE,
  BUILDING_MODE__SELECTING_CELL,
  BUILDING_MODE__SELECTING_AREA,
  BUILDING_MODE__PLACING_ENTRANCE,
  BUILDING_MODE__READY_FOR_OBJECTS,
  BUILDING_MODE__PLACING_OBJECTS,
  BUILDING_MODE__READY_TO_FINISH_ROOM,
  BUILDING_MODE__ROOM_FINISHED,
  BUILDING_MODE__CANT_BUILD,
  FURNITURE_MODE__PLACING_OBJECT,
  FURNITURE_MODE__FINISH_PLACEMENT,
  HIRING_STAFF_MODE,
  GAME_OVER
}
